//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonInfoManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string HIGH { get; set; }
        public string WEIGHT { get; set; }
        public string WORKOR { get; set; }
        public string IMAGE { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
    }
}
